### ISSUE TITLE
Allow anonymous support

### ISSUE THREAD

**Issue by froger** [octree-gva/fidbee#1]
Would be great to be able to submit bug report without giving an email. I would propose to have a form organized this way:
```
# Linked to an account
Bug: 
____________
____________

[SCREENSHOT]

[x] I agree to be contacted in order to solve this bug
email: [_______________]

[cancel] [SUBMIT]
```

```
# Anonymous
Bug: 
____________
____________

[SCREENSHOT]

[ ] I agree to be contacted in order to solve this bug

[cancel] [SUBMIT]
```

**Comment by 5ika** [comment]
Thanks @froger. Added to the [backlog](https://github.com/orgs/octree-gva/projects/4).

**Comment by 5ika** [comment]
In order to have a flexible component: the ability to support anonymous report will be configurable through a boolean props `allowAnonymous` on the Fidbee component.
